version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    build: ./live-builds/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  mysql-8:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    container_name: mysql-8
    ports:
      - "33060:3306"
    volumes:
      - ./db-data:/var/lib/mysql:delegated
    working_dir: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  php-fpm-82:
    container_name: php-fpm-82
    build: live-builds/php-fpm-82
    volumes:
      - ../:/var/www/
    working_dir: /var/www
    links:
      - mysql-8

  2023-bielecki:
    container_name: 2023-bielecki
    build: ./live-builds/2023-bielecki
    environment:
      - VIRTUAL_HOST=bielecki.test
    volumes:
      - ../2023-bielecki:/var/www/2023-bielecki
    working_dir: /var/www/2023-bielecki
    depends_on:
      - php-fpm-82

  2023-divelog-api:
    container_name: 2023-divelog-api
    build: ./live-builds/2023-divelog-api
    environment:
      - VIRTUAL_HOST=divelog-api.test
    volumes:
      - ../2023-divelog-api:/var/www/2023-divelog-api
    working_dir: /var/www/2023-divelog-api
    depends_on:
      - php-fpm-82
